---

# --------------------------------------------------------------------------- #
# An orchestrator deployment configuration file (version 1).                  #
#                                                                             #
# Refer to the 'compact-aws-frankfurt-3-11' deployment configuration          #
# for a detailed discussion of the  properties defined in this file.          #
# --------------------------------------------------------------------------- #

version: 1

name: ORN DEV Deployment (OKD 3.11) [HPC2N]
description: >
  The deployment for the ORN DEV site.

# --- cluster -----------------------------------------------------------------

cluster:

  id: orn-dev-311

  name_tag: orn
  public_hostname: dev.openrisknet.org
  default_subdomain: dev.openrisknet.org
  api_port: 8443

  master:
    count: 1
    is_infra: no
    is_bastion: no
    is_compute_node: no

  infra:
    count: 1
    is_compute_node: no

  nodes:
  - count: 4
    node_group: compute

  glusterfs:
    count: 3

okd:

  ansible_tag: openshift-ansible-3.11.82-1
  ansible_version: 2.7.5
  play:
  - prerequisites
  - deploy_cluster

  post_okd:
  - play: acme-controller

  enable:
  - tsb
  - metrics

  certificates:
    generate_api_cert: yes

  inventory_dir: simple-os-3-11

# --- my_machines -------------------------------------------------------------

my_machines:

  cli_node: 130.239.81.149
  bastion: 130.239.81.208

  master1: 192.168.0.15

  infra1: 192.168.0.16

  node001: 192.168.0.7
  node002: 192.168.0.10
  node003: 192.168.0.18
  node004: 192.168.0.13

  glusterfs1: 192.168.0.22
  glusterfs2: 192.168.0.11
  glusterfs3: 192.168.0.5

  glusterfs1_device1: /dev/vdb
  glusterfs2_device1: /dev/vdb
  glusterfs3_device1: /dev/vdb

# -----------------------------------------------------------------------------
