---

dist: xenial
language: python
python:
- 3.7

services:
- docker

stages:
- analysis
- build

install:
- pip install -r build-requirements.txt
- pip install -r requirements.txt

jobs:
  include:
  # Analysis stage jobs...
  - stage: analysis
    script: build-scripts/static-analysis.sh
  - stage: analysis
    script: build-scripts/ansible-syntax-check.sh
  # Build stage jobs...
  - stage: build
    script: build-scripts/doc-build.sh
  - stage: build
    script: build-scripts/image-build.sh
