---

# To build and push the stable docker image: -
#
#   IMAGE_TAG=stable docker-compose build
#   IMAGE_TAG=stable docker-compose push

version: '3.3'

services:

  okd-orchestrator:
    build:
      context: .
    image: "informaticsmatters/okd-orchestrator:${IMAGE_TAG:-latest}"
    container_name: okd-orchestrator
