---

# To build and push the latest (test) docker image: -
#
#   docker-compose build
#   docker-compose push
#
# To build and push the stable (official) docker image: -
#
#   IMAGE_TAG=stable docker-compose build
#   IMAGE_TAG=stable docker-compose push

version: '3.4'

services:

  okd-orchestrator:
    build:
      context: .
      network: host
    image: "informaticsmatters/okd-orchestrator:${IMAGE_TAG:-latest}"
    container_name: okd-orchestrator
    network_mode: host
