---

# This playbook should run an a CLI node
# (typically the cluster bastion or master).
# It executes post-OKD installation actions such as: -
#
# - Deploying templates
#
# These tasks only execute if 'template_namespace' is defined.
# If it is defined we also expect 'deployment' to be defined
# (which directs us to the template directory).

- hosts: cli-node

  tasks:

  - name: Login (admin)
    shell: >
      oc login {{ okd_api_hostname }}
      --insecure-skip-tls-verify=true
      -u admin -p {{ okd_admin_password }}
    changed_when: False
    when:
    - template_namespace is defined

  # Create the template project?

  - name: Get projects
    shell: oc get projects
    register: projects_result
    changed_when: False
    when:
    - template_namespace is defined

  - name: Create Template Project
    shell: >
      oc new-project {{ template_namespace }}
      --display-name="The Template Project"
      --description="A location where application Templates can be found"
    when:
    - template_namespace is defined
    - not projects_result.stdout
      | regex_search('^%s\s' % template_namespace, multiline=True)

  # Add the developer user?
  - name: Add Developer to Template Project
    shell: >
      oc adm policy add-role-to-user edit developer -n {{ template_namespace }}
    when:
    - template_namespace is defined
    - not projects_result.stdout
      | regex_search('^%s\s' % template_namespace, multiline=True)
    - okd_developer_password is defined

  # Deploy templates from the configuration's 'templates' directory...

  - name: Deploy configuration templates
    shell: oc create -f {{ item }} -n {{ template_namespace }}
    with_fileglob:
    - "../../deployments/{{ okd_deployment }}/templates/*"
    when:
    - template_namespace is defined
