---

# --------------------------------------------------------------------------- #
# An orchestrator deployment configuration file (version 1).                  #
#                                                                             #
# Refer to the 'compact-aws-frankfurt-3-11' deployment configuration          #
# for a detailed discussion of the  properties defined in this file.          #
# --------------------------------------------------------------------------- #

version: 1

name: Simple AWS Deployment (OKD 3.11) [Frankfurt]
description: >
  A simple deployment that forms separate Bastion, Master and Infra instances.
  This also includes certbot certificate creation, metrics and prometheus.

cluster:

  region: eu-central-1
  id: simple-frankfurt-311
  image_prefix: okd-machine-image-311-
  name_tag: vre-simple
  public_hostname: vre.informaticsmatters.com
  default_subdomain: apps.vre.informaticsmatters.com
  api_port: 8443
  terraform_dir: aws

  bastion:
    image_prefix: okd-bastion-image-311-
    type: t2.small

  master:
    count: 1
    type: t2.xlarge
    fixed_ip_id: eipalloc-010cfe12a8b8c7fa2

  infra:
    count: 1
    type: t2.xlarge
    fixed_ip_id: eipalloc-037f7a1943abe1174

  node_groups:
  - name: general
    labels:
    - general-node=true
    - super-node=true
    is_compute_node: yes

  nodes:
  - name: general
    count: 1
    type: t2.large
    node_group: general

okd:

  ansible_tag: openshift-ansible-3.11.83-1
  ansible_version: 2.7.5
  play:
  - prerequisites
  - deploy_cluster

  post_okd:
  - play: acme-controller

  enable:
  - metrics
  - prometheus
  - tsb
  - asb

  certificates:
    generate_api_cert: no

  inventory_dir: simple-aws-3-11
