---

# To build the stable docker image: -
#
#   IMAGE_TAG=stable docker-compose build

version: '3.6'

services:

  okd-orchestrator:
    build:
      context: .
    image: "informaticsmatters/okd-orchestrator:${IMAGE_TAG:-latest}"
    container_name: okd-orchestrator
