---

# This playbook interacts with the bastion node.

# It includes installation of `terraform` - a tool required to
# orchestrate the cluster. Binary tools are installed in
# the user's `~/bin` directory if they don't already exist.

- hosts: bastion
  gather_facts: no

  tasks:

  # --------
  # Preamble
  # --------

  # Wait for the the host...
  - name: Wait for SSH
    wait_for:
      host: "{{ ansible_ssh_host }}"
      port: 22
      search_regex: OpenSSH
      delay: 5
    vars:
      ansible_connection: local

  - name: Gathering facts
    setup:

  - name: Create remote_tmp
    file:
      path: "{{ ansible_env.HOME }}/.ansible/tmp"
      state: directory
      mode: 0755

  # And files...

  - name: Install SSH private key
    copy:
      src: "{{ lookup('env','HOME') }}/.ssh/id_rsa"
      dest: "{{ ansible_env.HOME }}/.ssh/id_rsa"
      mode: 0600

  # Default environment variables

  # The path to the deployment-specific directory
  # is relative to this (ansible/bastion) directory.
  - name: Install bastion.sh
    copy:
      src: "../../openshift/inventories/{{ deployment }}/bastion.sh"
      dest: "/etc/profile.d/okd.sh"
      mode: 0644
    become: true

  # ----------------
  # The Orchestrator
  # ----------------

  - name: Clone this orchestrator
    git:
      repo: "{{ git_repo }}"
      dest: "{{ ansible_env.HOME }}/okd-orchestrator"

  # Copy the cluster inventory file generated by the OKD orchestrator
  # to the OKD clone directory on the Bastion. This inventory is required
  # to continue the OpenShift installation from the Bastion.
  - name: Copy cluster inventory
    copy:
      src: "../../openshift/inventories/{{ deployment }}/inventory"
      dest: "{{ ansible_env.HOME }}/okd-orchestrator/openshift/inventories/{{ deployment }}/inventory"
      mode: 0644
    become: true

  # Copy the bastion inventory file generated by the OKD orchestrator
  # to the OKD clone directory on the Bastion. This inventory is required
  # to continue the OpenShift installation from the Bastion.
  - name: Copy cluster inventory
    copy:
      src: "../../ansible/post-os/inventory"
      dest: "{{ ansible_env.HOME }}/okd-orchestrator/ansible/post-os/inventory"
      mode: 0644
    become: true

  # --------
  # Packages
  # --------

  - name: Install the libselinux-python package
    yum:
      name: libselinux-python
      state: present
