---

# --------------------------------------------------------------------------- #
# An orchestrator deployment configuration file (version 1).                  #
#                                                                             #
# Refer to the 'compact-aws-frankfurt-3-11' deployment configuration          #
# for a detailed discussion of the  properties defined in this file.          #
# --------------------------------------------------------------------------- #

#
# Do Not Use      =--->   U N D E R  C O N S T R U C T I O N   <---=
#

version: 1

name: ORN BEAR Deployment (OKD 3.11)
description: >
  The deployment for the University of Birmingham ORN BEAR-Cloud site.

# --- cluster -----------------------------------------------------------------

cluster:

  id: orn-dev-311

  name_tag: orn
  public_hostname: bear.openrisknet.org
  default_subdomain: apps.bear.openrisknet.org
  api_port: 443

  master:
    count: 1
    is_infra: no
    is_bastion: yes
    is_compute_node: yes

  infra:
    count: 1
    is_compute_node: yes

  nodes:
  - count: 1
    node_group: compute

  glusterfs:
    count: 3

okd:

  ansible_tag: openshift-ansible-3.11.102-1
  ansible_version: 2.7.9
  play:
#  - openshift-glusterfs/uninstall
#  - adhoc/uninstall
  - prerequisites
  - deploy_cluster

  post_okd:
  - play: acme-controller

  enable:
  - asb
  - tsb
  - metrics
  - prometheus

  certificates:
    generate_api_cert: yes

  inventory_dir: standard-os-3-11

# --- my_machines -------------------------------------------------------------

my_machines:

  cli_node: master-name
  bastion: master-name

  master1: master-name

  infra1: infra-name

  node001: node-name

  glusterfs1: master-name
  glusterfs2: infra-name
  glusterfs3: node-name

  glusterfs1_device1: /dev/vdb
  glusterfs2_device1: /dev/vdb
  glusterfs3_device1: /dev/vdb

# -----------------------------------------------------------------------------
