---

# --------------------------------------------------------------------------- #
# An orchestrator deployment configuration file (version 1).                  #
#                                                                             #
# Refer to the 'compact-aws-frankfurt-3-11' deployment configuration          #
# for a detailed discussion of the  properties defined in this file.          #
# --------------------------------------------------------------------------- #

version: 1

name: ORN JGU Deployment (OKD 3.11)
description: >
  The deployment for the University of Mainz site.

# --- cluster -----------------------------------------------------------------

cluster:

  id: orn-jgu-311

  name_tag: orn
  public_hostname: prod.openrisknet.org
  default_subdomain: prod.openrisknet.org
  api_port: 443

  master:
    count: 1
    is_infra: no
    is_bastion: no
    is_compute_node: no

  infra:
    count: 1
    is_compute_node: no

  nfs:
    machine: infra1

  nodes:
  - count: 3
    node_group: compute

okd:

  ansible_tag: openshift-ansible-3.11.154-1
  ansible_version: 2.7.13
  play:
#  - openshift-glusterfs/uninstall
#  - adhoc/uninstall
  - prerequisites
  - deploy_cluster

  post_okd:
  - play: acme-controller

  storage:
    metrics: 40Gi
    registry: 200Gi

  enable:
  - metrics
  - tsb
#  - asb

  certificates:
    master_api_cert: prod.openrisknet.org

  inventory_dir: nfs-3-11

# --- my_machines -------------------------------------------------------------

my_machines:

  cli_node: cloudv200.zdv.uni-mainz.de
  bastion: cloudv198.zdv.uni-mainz.de

  master1: cloudv200.zdv.uni-mainz.de

  infra1: cloudv199.zdv.uni-mainz.de

  node001: cloudv201.zdv.uni-mainz.de
  node002: cloudv202.zdv.uni-mainz.de
  node003: cloudv203.zdv.uni-mainz.de

# -----------------------------------------------------------------------------
