---

# --------------------------------------------------------------------------- #
# An orchestrator deployment configuration file (version 1).                  #
#                                                                             #
# Refer to the 'compact-aws-frankfurt-3-11' deployment configuration          #
# for a detailed discussion of the  properties defined in this file.          #
# --------------------------------------------------------------------------- #

version: 1

name: ORN PROD Deployment (OKD 3.11) [UPPMAX]
description: >
  The deployment for the ORN PROD site.

# --- cluster -----------------------------------------------------------------

cluster:

  id: orn-prod-311

  name_tag: orn
  public_hostname: 130.238.28.112.nip.io
  default_subdomain: 130.238.28.144.nip.io
  api_port: 443

  master:
    count: 1
    is_infra: no
    is_bastion: no
    is_compute_node: no

  infra:
    count: 1
    is_compute_node: no

  nodes:
  - count: 5
    node_group: compute

  glusterfs:
    count: 5

okd:

  ansible_tag: openshift-ansible-3.11.129-1
  ansible_version: 2.7.12
  play:
  #  - openshift-glusterfs/uninstall
  #  - adhoc/uninstall
  - prerequisites
  - deploy_cluster

  post_okd:
  - play: acme-controller

  enable:
  - tsb
  - metrics
  - prometheus

  certificates:
    generate_api_cert: no

  inventory_dir: standard-os-3-11

# --- my_machines -------------------------------------------------------------

my_machines:

  cli_node: prod-master.openstacklocal
  bastion: 130.238.28.49

  master1: prod-master.openstacklocal

  infra1: prod-infra.openstacklocal

  node001: prod-node-001.openstacklocal
  node002: prod-node-002.openstacklocal
  node003: prod-node-003.openstacklocal
  node004: prod-node-004.openstacklocal
  node005: prod-node-005.openstacklocal

  glusterfs1: prod-gluster-001.openstacklocal
  glusterfs2: prod-gluster-002.openstacklocal
  glusterfs3: prod-gluster-003.openstacklocal
  glusterfs4: prod-gluster-004.openstacklocal
  glusterfs5: prod-gluster-005.openstacklocal

  glusterfs1_device1: /dev/vdb
  glusterfs2_device1: /dev/vdb
  glusterfs3_device1: /dev/vdb
  glusterfs4_device1: /dev/vdb
  glusterfs5_device1: /dev/vdb

# -----------------------------------------------------------------------------
