---

# --------------------------------------------------------------------------- #
# An orchestrator deployment configuration file (version 1).                  #
#                                                                             #
# Refer to the 'compact-aws-frankfurt-3-11' deployment configuration          #
# for a detailed discussion of the  properties defined in this file.          #
# --------------------------------------------------------------------------- #

version: 1

name: ORN PROD Deployment (OKD 3.11) [UPPMAX]
description: >
  The deployment for the ORN PROD site.

# --- cluster -----------------------------------------------------------------

cluster:

  id: orn-prod-311

  name_tag: orn
  public_hostname: 130.238.28.112.nip.io
  default_subdomain: 130.238.28.144.nip.io
  api_port: 443

  master:
    count: 1
    is_infra: no
    is_bastion: no
    is_compute_node: no

  infra:
    count: 1
    is_compute_node: no

  nodes:
  - count: 5
    node_group: compute

  glusterfs:
    count: 5

okd:

  ansible_tag: openshift-ansible-3.11.129-1
  ansible_version: 2.7.12
  play:
  - prerequisites
  - deploy_cluster

  post_okd:
  - play: acme-controller

  enable:
  - tsb
  - metrics
  - prometheus

  certificates:
    generate_api_cert: no

  inventory_dir: standard-os-3-11

# --- my_machines -------------------------------------------------------------

my_machines:

  cli_node: 10.0.0.11
  bastion: 130.238.28.49

  master1: 10.0.0.11

  infra1: 10.0.0.25

  node001: 10.0.0.14
  node002: 10.0.0.29
  node003: 10.0.0.6
  node004: 10.0.0.26
  node005: 10.0.0.27

  glusterfs1: 10.0.0.35
  glusterfs2: 10.0.0.5
  glusterfs3: 10.0.0.18
  glusterfs4: 10.0.0.39
  glusterfs5: 10.0.0.7

  glusterfs1_device1: /dev/vdb
  glusterfs2_device1: /dev/vdb
  glusterfs3_device1: /dev/vdb
  glusterfs4_device1: /dev/vdb
  glusterfs5_device1: /dev/vdb

# -----------------------------------------------------------------------------
