---

# --------------------------------------------------------------------------- #
# An orchestrator deployment configuration file (version 1).                  #
#                                                                             #
# Refer to the 'compact-aws-frankfurt-3-11' deployment configuration          #
# for a detailed discussion of the  properties defined in this file.          #
# --------------------------------------------------------------------------- #

version: 1

name: ORN PROD Deployment (OKD 3.11) [UPPMAX]
description: >
  The deployment for the ORN PROD site.

# --- cluster -----------------------------------------------------------------

cluster:

  id: orn-prod-311

  name_tag: orn
  public_hostname: 130.238.28.?.nip.io
  default_subdomain: 130.238.28.?.nip.io
  api_port: 443

  master:
    count: 1
    is_infra: no
    is_bastion: no
    is_compute_node: no

  infra:
    count: 1
    is_compute_node: no

  nodes:
  - count: 8
    node_group: compute

  glusterfs:
    count: 3

okd:

  ansible_tag: openshift-ansible-3.11.128-1
  ansible_version: 2.7.12
  play:
  - prerequisites
  - deploy_cluster

  post_okd:
  - play: acme-controller

  enable:
  - tsb
  - metrics

  certificates:
    generate_api_cert: yes

  inventory_dir: standard-os-3-11

# --- my_machines -------------------------------------------------------------

my_machines:

  cli_node: 130.238.28.?
  bastion: 130.238.28.?

  master1: 10.0.0.?

  infra1: 10.0.0.?

  node001: 10.0.0.?
  node002: 10.0.0.?
  node003: 10.0.0.?
  node004: 10.0.0.?
  node005: 10.0.0.?
  node006: 10.0.0.?
  node007: 10.0.0.?
  node008: 10.0.0.?

  glusterfs1: 10.0.0.?
  glusterfs2: 10.0.0.?
  glusterfs3: 10.0.0.?

  glusterfs1_device1: /dev/vdb
  glusterfs2_device1: /dev/vdb
  glusterfs3_device1: /dev/vdb

# -----------------------------------------------------------------------------
