---
name: build

on:
- push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
        pip install -r requirements.txt
    - name: Static analysis
      run: |
        ./build-scripts/static-analysis.sh
        ./build-scripts/ansible-syntax-check.sh
    - name: Build docs
      run: |
        ./build-scripts/doc-build.sh
    - name: Setup buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Build image
      run: docker-compose build
